### ISSUE TITLE
Can't generate project for stm32f767zit6u

### ISSUE THREAD

**Issue by KapDecy** [burrbull/stm32-template#3]
While trying to generate project I get error:
🤷   What microcontroller name? [default: stm32f411ceu6]: stm32f767zit6u
Error: ⛔   Failed executing script: pre-script.rhai

Caused by:
    Function not found: + ((), i64) (line 244, position 21)

Can you help me or tell where i'm wrong?

**Comment by burrbull** [comment]
Thanks. Should be fixed now. Although I can't test it.
