### ISSUE TITLE
Cannot generate RTIC project

### ISSUE THREAD

**Issue by BarronE-MSOE** [burrbull/stm32-template#6]
Whenever using cargo generate to create an RTIC project, the pre-script.rhai script fails, outputting:

Caused by:
    Data type incorrect: string (expecting bool) (line 497, position 29)

Attempting to build for multiple different boards including just using default settings reproduces bug in all attempted instances. 

Below is the code which breaks:
```
if variable::get("rtic") && rtic_feature {
    hal_dependency += "\"${rtic_feature}\", "
}
```

**Comment by dboycepa** [comment]
It looks like 40c0a63adfe9f65182b1d8c4ac3d86fe89c57b46 (master) should fix this issue.
